// <auto-generated />
using System;
using Cochera.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cochera.Infrastructure.Migrations
{
    [DbContext(typeof(CocheraDbContext))]
    [Migration("20260302024350_AddIdentityAuth")]
    partial class AddIdentityAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cochera.Domain.Entities.Cajon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoCambioEstado")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Cajones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = 0,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = 1
                        },
                        new
                        {
                            Id = 2,
                            Estado = 0,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = 2
                        });
                });

            modelBuilder.Entity("Cochera.Domain.Entities.EstadoCochera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cajon1Ocupado")
                        .HasColumnType("boolean");

                    b.Property<bool>("Cajon2Ocupado")
                        .HasColumnType("boolean");

                    b.Property<int>("CajonesLibres")
                        .HasColumnType("integer");

                    b.Property<int>("CajonesOcupados")
                        .HasColumnType("integer");

                    b.Property<bool>("CocheraLlena")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("EstadosCochera");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cajon1Ocupado = false,
                            Cajon2Ocupado = false,
                            CajonesLibres = 2,
                            CajonesOcupados = 0,
                            CocheraLlena = false,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UltimaActualizacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cochera.Domain.Entities.EventoSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CajonesLibres")
                        .HasColumnType("integer");

                    b.Property<int>("CajonesOcupados")
                        .HasColumnType("integer");

                    b.Property<bool>("CocheraLlena")
                        .HasColumnType("boolean");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EstadoCajon1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EstadoCajon2")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EventoOriginal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("JsonOriginal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimestampESP32")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Cochera.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SesionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SesionId")
                        .IsUnique();

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Cochera.Domain.Entities.SesionEstacionamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CajonId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MinutosEstacionado")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TarifaPorMinuto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CajonId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("Cochera.Domain.Entities.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("PrecioPorMinuto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Tarifas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Descripcion = "Tarifa estándar",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrecioPorMinuto = 8.0m
                        });
                });

            modelBuilder.Entity("Cochera.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "admin",
                            EsAdmin = true,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "usuario_1",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Usuario 1"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "usuario_2",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Usuario 2"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "usuario_3",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Usuario 3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f7a1e7bf-3027-4e58-bb9d-3d95539b06b1",
                            ConcurrencyStamp = "3f748c6f-89ef-44a4-a5df-b6e11c3d6699",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "228f9a8f-5b1b-45c0-8b2e-c735e3e2f1df",
                            ConcurrencyStamp = "9cd40291-2524-4a53-844d-dfb89d897eb3",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f20c5015-e40a-4a96-b9eb-715ea40e861b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "af39c7f3-dd2c-4d91-a660-07ad4ec7b410",
                            Email = "admin@cochera.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@COCHERA.LOCAL",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAENvOSDp1AVWk207mYj6NOniKh5bTXYfQFfbUv+FgkNpqEs9ueukgqamRfcubauL57w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ba649f7f-6875-4542-94f4-5fb5052e54a8",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "53014967-9f8a-4c35-a315-ae5c8a4c47fd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "de040aa3-772f-4f14-9ff1-1a7fd51f2413",
                            Email = "usuario_1@cochera.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USUARIO_1@COCHERA.LOCAL",
                            NormalizedUserName = "USUARIO_1",
                            PasswordHash = "AQAAAAIAAYagAAAAEIFYLfIN3oeaUGY7JvfYbiBVkiW6Ud5JjuVzM63piTCA6lc+jLQvJcI4LcfRMh5MZg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d17a34f4-2bfd-40be-adba-f53e8b0f5a9c",
                            TwoFactorEnabled = false,
                            UserName = "usuario_1"
                        },
                        new
                        {
                            Id = "e5b8e407-9928-4e9e-a3ef-587f1b055fe6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1ad2c9bc-3fd9-4f13-b65a-2a95ecf5e8f7",
                            Email = "usuario_2@cochera.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USUARIO_2@COCHERA.LOCAL",
                            NormalizedUserName = "USUARIO_2",
                            PasswordHash = "AQAAAAIAAYagAAAAEEZqwkhkFrl9UUdjUxAw223Vr4DRhio7UYlhx7iYD1Lh9qoRYvcDgQ1Th3x0ScuzPQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "41fef75e-01fd-49e5-a467-2868cb131404",
                            TwoFactorEnabled = false,
                            UserName = "usuario_2"
                        },
                        new
                        {
                            Id = "49f95ed4-6ba5-4d36-9f20-8958410839a0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6f6d5f68-7a58-4c37-baf4-0ea61f60fc00",
                            Email = "usuario_3@cochera.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USUARIO_3@COCHERA.LOCAL",
                            NormalizedUserName = "USUARIO_3",
                            PasswordHash = "AQAAAAIAAYagAAAAECwNr3ykJ9PxbAET3DFHTz02pUTYPRnrgNeLN4o6eEs4QzIJkZu7scxztihMczdJ5w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "43981f52-dc35-4cf1-8702-a034ea7e7f53",
                            TwoFactorEnabled = false,
                            UserName = "usuario_3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "f20c5015-e40a-4a96-b9eb-715ea40e861b",
                            RoleId = "f7a1e7bf-3027-4e58-bb9d-3d95539b06b1"
                        },
                        new
                        {
                            UserId = "53014967-9f8a-4c35-a315-ae5c8a4c47fd",
                            RoleId = "228f9a8f-5b1b-45c0-8b2e-c735e3e2f1df"
                        },
                        new
                        {
                            UserId = "e5b8e407-9928-4e9e-a3ef-587f1b055fe6",
                            RoleId = "228f9a8f-5b1b-45c0-8b2e-c735e3e2f1df"
                        },
                        new
                        {
                            UserId = "49f95ed4-6ba5-4d36-9f20-8958410839a0",
                            RoleId = "228f9a8f-5b1b-45c0-8b2e-c735e3e2f1df"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Cochera.Domain.Entities.Pago", b =>
                {
                    b.HasOne("Cochera.Domain.Entities.SesionEstacionamiento", "Sesion")
                        .WithOne("Pago")
                        .HasForeignKey("Cochera.Domain.Entities.Pago", "SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("Cochera.Domain.Entities.SesionEstacionamiento", b =>
                {
                    b.HasOne("Cochera.Domain.Entities.Cajon", "Cajon")
                        .WithMany("Sesiones")
                        .HasForeignKey("CajonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cochera.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cajon");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cochera.Domain.Entities.Cajon", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("Cochera.Domain.Entities.SesionEstacionamiento", b =>
                {
                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Cochera.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
